from enum import Enum

class State(Enum):
    # Hand
    FREE = 0
    ANOTHER_LEFT_HAND_PALM = 1
    ANOTHER_LEFT_HAND_FOREARM = 2
    ANOTHER_LEFT_HAND_SHOULDER = 3
    ANOTHER_RIGHT_HAND_PALM = 4
    ANOTHER_RIGHT_HAND_FOREARM = 5
    ANOTHER_RIGHT_HAND_SHOULDER = 6
    ANOTHER_NECK = 7
    ANOTHER_CHEST = 8
    ANOTHER_STOMACH = 9
    ANOTHER_LEFT_SIDE = 10
    ANOTHER_RIGHT_SIDE = 11
    ANOTHER_TOP_HEAD = 12
    ANOTHER_LEFT_HIP = 13
    ANOTHER_LEFT_SHIN = 14
    ANOTHER_LEFT_FOOT = 15
    ANOTHER_RIGHT_HIP = 16
    ANOTHER_RIGHT_SHIN = 17
    ANOTHER_RIGHT_FOOT = 18
    ANOTHER_LEFT_SHOULDER_BLADE = 19
    ANOTHER_RIGHT_SHOULDER_BLADE = 20
    ANOTHER_LOWER_BACK = 21
    # Legs
    KNEE = 100
    SQUAT = 101

class Side(Enum):
    LEFT = 0
    RIGHT = 1

class Role(Enum):
    LEADING = 0
    FOLLOWER = 1

class Weight(Enum):
    ZERO = 0
    QUARTER = 0.25
    HALF = 0.5
    THREE_QUARTERS = 0.75
    WHOLE = 1
